In [1]:
import yaml
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [13]:
with open("../config.yaml",'r') as file:
    config = yaml.safe_load(file)

In [14]:
config

{'data': {'raw': {'file1': '../data/raw/LeadScoring.csv',
   'file2': '../data/raw/Leads_Data_Dictionary.csv',
   'file3': '../data/raw/digital_marketing_campaign_dataset.csv',
   'file4': '../data/raw/bank.csv',
   'file5': '../data/raw/bank-full.csv',
   'file6': '../data/raw/bank-additional.csv',
   'file7': '../data/raw/bank-additional-full.csv',
   'file8': '../data/raw/marketing_campaign.csv'},
  'clean': {'file1': '../data/clean/leadscoring.csv',
   'file2': '../data/clean/bank-full.csv',
   'file3': '../data/clean/ready_to_model.csv',
   'file4': '../data/clean/ready_to_model_all_cols.csv',
   'file5': '../data/clean/marketing_campaign.csv'}}}

In [15]:
data = pd.read_csv(config['data']['clean']['file5'], quotechar='"', sep = ";")

In [16]:
data

,year_birth,education,marital_status,income,recency,wines,fruits,meat,fish,sweets,...,store,webvisits,complain,response,age,num_children,has_child,customer_tenure_in_days,total_spend,num_camp_success
0,1957,Postgraduate,Single,58138.0,58,635,88,546,172,88,...,4,7,0,1,57,0,False,665,1617,0
1,1954,Postgraduate,Single,46344.0,38,11,1,6,2,1,...,2,5,0,0,60,2,True,115,27,0
2,1965,Postgraduate,Partnered,71613.0,26,426,49,127,111,21,...,10,4,0,0,49,0,False,314,776,0
3,1984,Postgraduate,Partnered,26646.0,26,11,4,20,10,3,...,4,6,0,0,30,1,True,141,53,0
4,1981,PhD,Partnered,58293.0,94,173,43,118,46,27,...,6,5,0,0,33,1,True,163,422,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2210,1967,Postgraduate,Partnered,61223.0,46,709,43,182,42,118,...,4,5,0,0,47,1,True,383,1341,0
2211,1946,PhD,Partnered,64014.0,56,406,0,30,0,0,...,5,7,0,0,68,3,True,21,444,1
2212,1981,Postgraduate,Separated,56981.0,91,908,48,217,32,12,...,13,6,0,0,33,0,False,157,1241,1
2213,1956,Postgraduate,Partnered,69245.0,8,428,30,214,80,30,...,10,3,0,0,58,1,True,158,843,0
2214,1954,PhD,Partnered,52869.0,40,84,3,61,2,1,...,4,7,0,1,60,2,True,624,172,0

In [17]:
data.select_dtypes('number').corr()

,year_birth,income,recency,wines,fruits,meat,fish,sweets,gold,deals,...,catalogue,store,webvisits,complain,response,age,num_children,customer_tenure_in_days,total_spend,num_camp_success
year_birth,1.000000,-0.198064,-0.016023,-0.159225,-0.017653,-0.033499,-0.040265,-0.020013,-0.064030,-0.058953,...,-0.121610,-0.127660,0.123833,-0.030380,0.023825,-1.000000,-0.087429,0.020249,-0.113241,-0.002154
income,-0.198064,1.000000,0.006945,0.688269,0.507959,0.692465,0.520351,0.523746,0.389204,-0.108457,...,0.696541,0.630397,-0.650564,-0.030583,0.161049,0.198064,-0.344035,-0.024126,0.792650,0.366384
recency,-0.016023,0.006945,1.000000,0.015370,-0.005971,0.022254,0.000331,0.024859,0.017417,0.002470,...,0.023856,-0.000784,-0.018453,0.013599,-0.199981,0.016023,0.018322,0.026045,0.019706,-0.013829
wines,-0.159225,0.688269,0.015370,1.000000,0.386977,0.568752,0.397602,0.390178,0.392588,0.009235,...,0.634684,0.639889,-0.321928,-0.039516,0.246185,0.159225,-0.353782,0.168155,0.893098,0.510770
fruits,-0.017653,0.507959,-0.005971,0.386977,1.000000,0.547796,0.593407,0.571581,0.396443,-0.134416,...,0.486229,0.458457,-0.418706,-0.005338,0.122391,0.017653,-0.395900,0.067987,0.613249,0.157039
meat,-0.033499,0.692465,0.022254,0.568752,0.547796,1.000000,0.573507,0.535048,0.359328,-0.121079,...,0.734082,0.485877,-0.539464,-0.023814,0.237653,0.033499,-0.504574,0.089644,0.845853,0.307102
fish,-0.040265,0.520351,0.000331,0.397602,0.593407,0.573507,1.000000,0.583804,0.427056,-0.143062,...,0.532692,0.457641,-0.446392,-0.021246,0.108054,0.040265,-0.427852,0.081887,0.642311,0.176023
sweets,-0.020013,0.523746,0.024859,0.390178,0.571581,0.535048,0.583804,1.000000,0.357336,-0.121214,...,0.495054,0.455096,-0.422336,-0.022671,0.116065,0.020013,-0.389426,0.081048,0.606970,0.201386
gold,-0.064030,0.389204,0.017417,0.392588,0.396443,0.359328,0.427056,0.357336,1.000000,0.052161,...,0.442340,0.389039,-0.247638,-0.031163,0.140232,0.064030,-0.268922,0.160573,0.528599,0.196725
deals,-0.058953,-0.108457,0.002470,0.009235,-0.134416,-0.121079,-0.143062,-0.121214,0.052161,1.000000,...,-0.011897,0.066468,0.346003,0.000536,0.003617,0.058953,0.436123,0.218463,-0.065521,-0.125581
web,-0.152951,0.458812,-0.005803,0.553745,0.302001,0.307013,0.299621,0.333866,0.407005,0.241646,...,0.386808,0.516191,-0.051179,-0.016660,0.151367,0.152951,-0.148864,0.192805,0.528928,0.196760
catalogue,-0.121610,0.696541,0.023856,0.634684,0.486229,0.734082,0.532692,0.495054,0.442340,-0.011897,...,1.000000,0.517743,-0.521979,-0.020866,0.219830,0.121610,-0.443489,0.097668,0.780450,0.346148
store,-0.127660,0.630397,-0.000784,0.639889,0.458457,0.485877,0.457641,0.455096,0.389039,0.066468,...,0.517743,1.000000,-0.432369,-0.016982,0.036085,0.127660,-0.323240,0.112712,0.675067,0.202615
webvisits,0.123833,-0.650564,-0.018453,-0.321928,-0.418706,-0.539464,-0.446392,-0.422336,-0.247638,0.346003,...,-0.521979,-0.432369,1.000000,0.019798,-0.002156,-0.123833,0.416075,0.275999,-0.499068,-0.165456
complain,-0.030380,-0.030583,0.013599,-0.039516,-0.005338,-0.023814,-0.021246,-0.022671,-0.031163,0.000536,...,-0.020866,-0.016982,0.019798,1.000000,-0.002048,0.030380,0.031777,0.033288,-0.037475,-0.022408
response,0.023825,0.161049,-0.199981,0.246185,0.122391,0.237653,0.108054,0.116065,0.140232,0.003617,...,0.219830,0.036085,-0.002156,-0.002048,1.000000,-0.023825,-0.167642,0.196525,0.264015,0.427076
age,-1.000000,0.198064,0.016023,0.159225,0.017653,0.033499,0.040265,0.020013,0.064030,0.058953,...,0.121610,0.127660,-0.123833,0.030380,-0.023825,1.000000,0.087429,-0.020249,0.113241,0.002154
num_children,-0.087429,-0.344035,0.018322,-0.353782,-0.395900,-0.504574,-0.427852,-0.389426,-0.268922,0.436123,...,-0.443489,-0.323240,0.416075,0.031777,-0.167642,0.087429,1.000000,-0.025948,-0.500308,-0.245888
customer_tenure_in_days,0.020249,-0.024126,0.026045,0.168155,0.067987,0.089644,0.081887,0.081048,0.160573,0.218463,...,0.097668,0.112712,0.275999,0.033288,0.196525,-0.020249,-0.025948,1.000000,0.158685,-0.011972
total_spend,-0.113241,0.792650,0.019706,0.893098,0.613249,0.845853,0.642311,0.606970,0.528599,-0.065521,...,0.780450,0.675067,-0.499068,-0.037475,0.264015,0.113241,-0.500308,0.158685,1.000000,0.457020
num_camp_success,-0.002154,0.366384,-0.013829,0.510770,0.157039,0.307102,0.176023,0.201386,0.196725,-0.125581,...,0.346148,0.202615,-0.165456,-0.022408,0.427076,0.002154,-0.245888,-0.011972,0.457020,1.000000

In [18]:
data.columns

Index(['year_birth', 'education', 'marital_status', 'income', 'recency',
       'wines', 'fruits', 'meat', 'fish', 'sweets', 'gold', 'deals', 'web',
       'catalogue', 'store', 'webvisits', 'complain', 'response', 'age',
       'num_children', 'has_child', 'customer_tenure_in_days', 'total_spend',
       'num_camp_success'],
      dtype='str')

pca_cols = wines,fruits, meat,fish,sweets,gold
cluster_cols=deals, web,catalog, has_child, num_children, income, pca results
cluster_characteristics=year_birth,education, marital_status
prediction= ['recency', 'num_camp_success', 'deals', 'webvisits', 'customer_tenure_in_days', 'age', 'education', 'marital_status'] + your final Cluster Labels.

┌───────────────────────────────────────────────┐
               │    Final Classifier (Predicting: response)    │
               └───────────────────────┬───────────────────────┘
                                       │
        ┌──────────────────────────────┴──────────────────────────────┐
        ▼                                                             ▼
[ Team Demographics / Capacity ]                             [ Team Digital / Intent ]
──► Cluster_Labels (built on spend/income)                   ──► webvisits (monthly traffic noise)
──► age                                                      ──► web (online transactions)
──► education / marital_status                               ──► deals (coupon hunting)
──► customer_tenure_in_days (loyalty)                        ──► recency (days since last action)

In [20]:
pca_cols=['wines','fruits','meat','fish','sweets','gold']
pca_data=data[pca_cols]

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
pca_data_scaled = scaler.fit_transform(pca_data)

In [27]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(pca_data_scaled)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >=0.75) +1
d,cumsum

(np.int64(3),
 array([0.56376933, 0.6879753 , 0.80156457, 0.87339009, 0.94155965,
        1.        ]))

In [28]:
# 1. Transform your scaled data into the 3 components
pca_3 = PCA(n_components=3)
X_pca = pca_3.fit_transform(pca_data_scaled)

# 2. Turn it into a dataframe
df_pca = pd.DataFrame(X_pca, columns=['Spend_PC1', 'Spend_PC2', 'Spend_PC3'])

# 3. Combine with your core demographics and channels for K-Means
X_cluster = pd.concat([
    df_pca, 
    data[['income', 'has_child', 'web', 'catalogue', 'store']].reset_index(drop=True)
], axis=1)

In [29]:
X_cluster_scaled = scaler.fit_transform(X_cluster)

In [39]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
for k in range(2, 11):
    km = KMeans(n_clusters=k, random_state=0)
    labels = km.fit_predict(X_cluster_scaled)
    score = silhouette_score(X_cluster_scaled, labels)
    print(f"k={k}: silhouette={score:.4f} inertia={km.inertia_}")

k=2: silhouette=0.3850 inertia=11245.213614702763
k=3: silhouette=0.3636 inertia=9209.584833725106
k=4: silhouette=0.3576 inertia=8229.595138919569
k=5: silhouette=0.3481 inertia=7498.024193086358
k=6: silhouette=0.3516 inertia=7101.1496699600175
k=7: silhouette=0.3297 inertia=6686.994008524706
k=8: silhouette=0.2691 inertia=6246.831584972244
k=9: silhouette=0.2463 inertia=6061.46141531877
k=10: silhouette=0.2438 inertia=5900.267679415193

In [43]:
final_kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
data['Cluster'] = final_kmeans.fit_predict(X_cluster_scaled)

# 2. Check the size of each cluster
print("Customers per cluster:")
print(data['Cluster'].value_counts())

# 3. Profile them using your key thesis columns
profile_cols = ['income', 'age', 'has_child', 'wines', 'meat', 'webvisits', 'total_spend','num_children']
print(data.groupby('Cluster')[profile_cols].mean())

Customers per cluster:
Cluster
0    1061
2     643
1     511
Name: count, dtype: int64

--- Demographics per Cluster ---
               income        age  has_child       wines        meat  \
Cluster
0        34724.505184  43.114043   0.878417   45.153629   24.293120
1        76451.154599  45.900196   0.066536  604.675147  474.000000
2        60970.455677  48.027994   0.958009  496.387247  158.718507

         webvisits  total_spend  num_children
Cluster
0         6.456173   103.536287      1.241282
1         2.667319  1383.455969      0.072407
2         5.548989   821.802488      1.157076

In [102]:
feature_cols= ['recency', 'num_camp_success', 'deals', 'webvisits','total_spend', 'income', 'customer_tenure_in_days', 'age', 'education', 'marital_status','Cluster'] 
features = data[feature_cols]
target= data.response

In [103]:
mapping = {
    'Undergraduate': 0,
    'Postgraduate': 1,
    'PhD': 2
}

features['education'] = features['education'].map(mapping)

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.20, random_state=0)

In [105]:
X_train

,recency,num_camp_success,deals,webvisits,total_spend,income,customer_tenure_in_days,age,education,marital_status,Cluster
202,21,0,10,7,541,46014.0,526,40,1,Partnered,2
1363,26,0,6,5,396,56243.0,183,39,1,Single,2
15,51,0,3,8,96,41850.0,554,34,1,Partnered,0
1504,21,0,1,3,1662,69930.0,401,43,1,Partnered,1
118,51,0,2,6,90,54348.0,23,61,1,Partnered,0
...,...,...,...,...,...,...,...,...,...,...,...
1033,91,0,1,4,122,33585.0,279,48,1,Partnered,0
1731,95,0,3,5,882,69901.0,398,45,1,Separated,2
763,64,0,2,6,93,40760.0,305,49,2,Single,0
835,79,0,2,5,195,49980.0,251,51,1,Single,0
1653,49,2,2,7,265,37929.0,336,29,2,Single,0

In [106]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, drop='first') # To avoid having an sparse_matrix as output

ohe.fit(X_train[['marital_status']]) # The .fit() method determines the unique values of each column
X_train_trans_np = ohe.transform(X_train[['marital_status']])
X_train_trans_np

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], shape=(1772, 2))

In [107]:
X_train_trans_df = pd.DataFrame(X_train_trans_np, columns=ohe.get_feature_names_out(), index=X_train.index)
X_train_trans_df

      marital_status_Separated  marital_status_Single
202                        0.0                    0.0
1363                       0.0                    1.0
15                         0.0                    0.0
1504                       0.0                    0.0
118                        0.0                    0.0
...                        ...                    ...
1033                       0.0                    0.0
1731                       1.0                    0.0
763                        0.0                    1.0
835                        0.0                    1.0
1653                       0.0                    1.0

[1772 rows x 2 columns]

In [108]:
X_test_trans_np = ohe.transform(X_test[['marital_status']])
X_test_trans_np

array([[0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [109]:
X_test_trans_df = pd.DataFrame(X_test_trans_np, columns=ohe.get_feature_names_out(), index=X_test.index)
X_test_trans_df

      marital_status_Separated  marital_status_Single
2210                       0.0                    0.0
98                         0.0                    0.0
982                        0.0                    1.0
1971                       0.0                    0.0
39                         0.0                    0.0
...                        ...                    ...
1732                       0.0                    0.0
2108                       0.0                    1.0
1193                       0.0                    0.0
1490                       0.0                    0.0
85                         0.0                    0.0

[443 rows x 2 columns]

In [110]:
X_train_full = pd.concat([X_train_trans_df, X_train.drop(columns=['marital_status'])], axis=1)
X_test_full  = pd.concat([X_test_trans_df, X_test.drop(columns=['marital_status'])], axis=1)

std_scaler = StandardScaler()

std_scaler.fit(X_train_full)

X_train_full_np = std_scaler.transform(X_train_full)
X_test_full_np  = std_scaler.transform(X_test_full)

X_train_full_np_df = pd.DataFrame(X_train_full_np, columns=X_train_full.columns, index=X_train_full.index)
X_test_full_np_df  = pd.DataFrame(X_test_full_np, columns=X_test_full.columns, index=X_test_full.index)

In [111]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=100,
                             max_depth=20,class_weight="balanced")

In [112]:
forest.fit(X_train_full_np, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=20)

In [113]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
y_pred_test_rf = forest.predict(X_test_full_np_df)

print(f"MAE, {mean_absolute_error(y_pred_test_rf, y_test): .2f}")
print(f"MSE, {mean_squared_error(y_pred_test_rf, y_test): .2f}")
print(f"RMSE, {root_mean_squared_error(y_pred_test_rf, y_test): .2f}")
print(f"Accuracy score, {forest.score(X_test_full_np_df, y_test): .2f}")

MAE,  0.15
MSE,  0.15
RMSE,  0.39
Accuracy score,  0.85

C:\Users\clair\documents\ironhack\final_project\Final-Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\clair\documents\ironhack\final_project\Final-Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [114]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_test_rf))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91       372
           1       0.53      0.56      0.55        71

    accuracy                           0.85       443
   macro avg       0.72      0.73      0.73       443
weighted avg       0.85      0.85      0.85       443

In [115]:
pd.Series(
    forest.feature_importances_,
    index=X_train_full_np_df.columns
).sort_values(ascending=False)

recency                     0.163793
total_spend                 0.158841
customer_tenure_in_days     0.142530
num_camp_success            0.132300
income                      0.119677
age                         0.080635
webvisits                   0.066455
deals                       0.047140
education                   0.030493
Cluster                     0.024136
marital_status_Single       0.019795
marital_status_Separated    0.014206
dtype: float64

In [97]:
from imblearn.over_sampling import RandomOverSampler

over = RandomOverSampler(random_state=42)
X_train_over, y_train_over = over.fit_resample(X_train_full_np, y_train)

In [98]:
forest.fit(X_train_over, y_train_over)

RandomForestClassifier(class_weight='balanced', max_depth=20)

In [99]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
y_pred_test_rf = forest.predict(X_test_full_np_df)

print(f"MAE, {mean_absolute_error(y_pred_test_rf, y_test): .2f}")
print(f"MSE, {mean_squared_error(y_pred_test_rf, y_test): .2f}")
print(f"RMSE, {root_mean_squared_error(y_pred_test_rf, y_test): .2f}")
print(f"Accuracy score, {forest.score(X_test_full_np_df, y_test): .2f}")

MAE,  0.14
MSE,  0.14
RMSE,  0.38
Accuracy score,  0.86

C:\Users\clair\documents\ironhack\final_project\Final-Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\clair\documents\ironhack\final_project\Final-Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [100]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_test_rf))

              precision    recall  f1-score   support

           0       0.90      0.93      0.92       372
           1       0.57      0.48      0.52        71

    accuracy                           0.86       443
   macro avg       0.74      0.70      0.72       443
weighted avg       0.85      0.86      0.85       443

In [101]:
pd.Series(
    forest.feature_importances_,
    index=X_train_full_np_df.columns
).sort_values(ascending=False)

recency                     0.201565
customer_tenure_in_days     0.192007
num_camp_success            0.191092
age                         0.117015
webvisits                   0.087204
deals                       0.068059
Cluster                     0.057712
education                   0.034811
marital_status_Single       0.029002
marital_status_Separated    0.021533
dtype: float64

In [52]:
X_train_standarised_df

NameError: name 'X_train_standarised_df' is not defined